env:
  es6: true
  browser: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 10
  sourceType: module
plugins:
  - prettier
rules:
  prettier/prettier: error
  no-unused-vars: error
  no-undef: error
extends:
  - plugin:prettier/recommended
