include:
  - project: development/tools/gitlab-ci-templates
    ref: master
    file: /nodejs/all-16.yml

variables:
  GITHUB_URL: git@github.com:Paciolan/remote-module-loader.git

stages:
  - build
  - test
  - publish

Build:
  # https://gitlabdev.paciolan.info/development/tools/gitlab-ci-templates/blob/master/nodejs/build.yml
  extends: .nodejs_build

Test:
  # https://gitlabdev.paciolan.info/development/tools/gitlab-ci-templates/blob/master/nodejs/lint_test_coverage.yml
  extends: .nodejs_lint_test_coverage

Publish:
  # https://gitlabdev.paciolan.info/development/tools/gitlab-ci-templates/-/blob/master/nodejs/publish_semantic_release.yml
  extends: .nodejs_publish_semantic_release
