include:
  - project: development/tools/gitlab-ci-templates
    ref: master
    file: /nodejs/all.yml

variables:
  GITHUB_URL: git@github.com:Paciolan/remote-module-loader.git

stages:
  - build
  - test
  - publish

Build:
  # https://gitlabdev.paciolan.info/development/tools/gitlab-ci-templates/blob/master/nodejs/build.yml
  extends: .nodejs_build

Test:
  # https://gitlabdev.paciolan.info/development/tools/gitlab-ci-templates/blob/master/nodejs/lint_test_coverage.yml
  extends: .nodejs_lint_test_coverage

Publish:
  # https://gitlabdev.paciolan.info/development/tools/gitlab-ci-templates/blob/master/nodejs/publish.yml
  extends: .nodejs_publish_semantic_release
  script:
    # set repository to github for npm link
    - node -e "require('fs').writeFileSync('./package.json', JSON.stringify(Object.assign(require('./package.json'), {repository:{type:'git',url:'$GITHUB_URL'}}), null, 2), 'utf8')"
